name = "memoProgClass2022w"
uuid = "e9393d5c-b878-4395-adee-268df1eb43dc"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
